const CONSTANTS = {
  THEMES:{
    LIGHT:'LIGHT',
    DARK:'DARK'
  },
  CHAT_TYPES:{
    DATA_ALL_RESPONSE_SUCCESS:"DATA_ALL_RESPONSE_SUCCESS",
    DATA_ALL_RESPONSE_ERROR:"DATA_ALL_RESPONSE_ERROR"
  }
}
export default CONSTANTS;