const CONSTANTS = {
  THEMES:{
    LIGHT:'LIGHT',
    DARK:'DARK'
  },
  CHAT_TYPES:{
    DATA_ALL_RESPONSE_SUCCESS:"DATA_ALL_RESPONSE_SUCCESS",
    DATA_ALL_RESPONSE_ERROR:"DATA_ALL_RESPONSE_ERROR"
  },
  MENU_TYPES_ACTION:{
    MENU_OPEN:"MENU_OPEN",
    MENU_CLOSE:"MENU_CLOSE",
  }
}
export default CONSTANTS;